# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Setup
title:            fourthcaponi
tagline:          'A Jekyll theme'
description:      'Welcome to my small corner of the internet. Please make yourself comfortable.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Michael Caponi'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
