# Dependencies
highlighter:      rouge

# Setup
title:            fourthcaponi
tagline:          'A Jekyll theme'
description:      'Welcome to my small corner of the internet. Please make yourself comfortable.'
url:              http://fourthcaponi.com
baseurl:          /

author:
  name:           'Michael Caponi'

paginate:         5

# Custom vars
version:          2.1.0

sidebar-links:
  email:      fourthcaponi@gmail.com
  facebook: 
  github:     fourthcaponi
  instagram:
  linkedin:   michael-caponi-iv
  rss: # just type anything here for a working RSS icon
  twitter:    fourthcaponi
